#!/bin/bash

for (( i = 0; i < 10; i++ )); do
  echo "hello mom"
done

matrixfile1=$2
matrixfile2=$3

rows=$( cat $matrixfile1 | wc -l ) #3
cols=$( cat $matrixfile1 | tail -1 | tr '\t' '\n' | wc -l ) #5

rows2=$( cat $matrixfile2 | wc -l ) #5
cols2=$( cat $matrixfile2 | tail -1 | tr '\t' '\n' | wc -l ) #3

if [[ $rows == "2" || "2" == $cols2 ]]
  then
    matrixfile1=$3
    matrixfile2=$2
  fi


cat $matrixfile1 | tr "\n" "\t" >> newfile2
cat $matrixfile2 | tr "\n" "\t" >> newfile2
echo "" >> newfile2

#cat newfile2

file2="newfile2"
counting1=`expr $counting1 + 1`
counting2=$(( $counting2 + ( rows * cols ) + 1 ))
increment3=`expr $increment3 + 1`
